using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace FakerLib.Test
{
    [TestClass]
    public class FooTest
    {
        [TestMethod]
        public void GetObjectTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetCharTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetBoolTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetByteTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetSByteTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetIntTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetUIntTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetShortTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetUShortTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetLongTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetULongTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetDecimalTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetFloatTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetDoubleTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetDateTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetStringTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetListTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetBarTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void OutputTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}